name: gettext-launch
version: current
summary: Remote part for fixing GNU Gettext-based localization
description: |
  This remote part fixes GNU Gettext-based localization by fixing the locale environment variables.
  
  Refer the snapcraft forum topic for more info regarding its usage:
  
      _topic_title_
      _topic_url_

grade: stable
confinement: strict

parts:
  gettext-launch:
    source: launchers
    plugin: dump
    organize:
      '*': bin/
    stage:
      - -bin/README.*
