name: gettext-launch
version: current
summary: Remote part for fixing GNU Gettext-based localization
description: |
  This remote part fixes GNU Gettext-based localization by fixing the locale environment variables.
  
  Refer the snapcraft forum topic for more info regarding its usage:
  
      The gettext-launch remote part - doc - snapcraft.io
      https://forum.snapcraft.io/t/the-gettext-launch-remote-part/9111

grade: stable
confinement: strict

parts:
  gettext-launch:
    source: launchers
    plugin: dump
    organize:
      '*': bin/
    stage:
      - -bin/README.*
